### ISSUE TITLE
Lora from ImpactWildcardEncode prompt not being imported to Civit

### ISSUE THREAD

**Issue by dalmackay** [alexopus/ComfyUI-Image-Saver#41]
![Screenshot 2024-09-05 223226](https://github.com/user-attachments/assets/0a0414d1-517b-41a2-8ef8-39ce495cbdee)
![Screenshot 2024-09-05 223242](https://github.com/user-attachments/assets/3c110f2a-5a35-4811-8c28-d23dbaf53298)

The Lora was downloaded from Civit just moments before generating, so the hashes match. 
The same happens when weight ":1.0" is on the end of lora name.

**Comment by vnguyen972** [comment]
First time I tried it few days ago.. it was working; now I reinstalled my ConfyUI and this nodes doesn't add Lora hashes anymore when I examine the metadata of the generated png 
Not sure what I missed this time.

**Comment by alexopus** [comment]
Glad it was solved.

**Comment by dalmackay** [comment]
It wasn't solved. They are not the OP. 

As I said in my post, I downloaded the Lora seconds before generating so my problem is different.

**Comment by alexopus** [comment]
![workflow](https://github.com/user-attachments/assets/8f6b6a49-f9fc-4e14-92f8-690785afe986)

In the image above is a working workflow, please check and compare what goes wrong for you. Result recognized by civitai fine:

![image](https://github.com/user-attachments/assets/70d7b6f4-a7c0-4697-89ed-8227ecaa9398)
